issuebot:
  github:
    username: svc-lmes-devops
    password: ${GITHUB_TOKEN} 
  monitoring:
    repositories:
      - organization: adeo
        name: lmes-devops-requests
        label_to_avoid_triage: "triaged"
        collaborators:
          - tfernandez-lmes
          - jmalvarezf-lmes
          - svc-lmes-devops
          - dheras-lmes
          - 30066646
          - ismazab
          - rgsopedra
          - AbrahamLM
          - jonefmc
  triage:
    label: "waiting-for-triage"
  feedback:
    required_label: "waiting-for-feedback"
    provided_label: "feedback-provided"
    reminder_label: "feedback-reminder"
    reminder_comment: >
      If you would like us to look at this issue, please provide the requested
      information. If the information is not provided within the next 7 days this issue
      will be closed.
    close_comment: >
      Closing due to lack of requested feedback. If you would like us to look at this
      issue, please provide the requested information and we will re-open the issue.

management:
  endpoint:
    health:
      show-details: always